apiVersion: v1
kind: Service
metadata:
  name: setup-a-ci-service
  labels:
    app: setup-a-ci
spec:
  selector:
    app: setup-a-ci
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
